e_voting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from . import views


urlpatterns = [
    path('', include('account.urls')),
    path('admin/', admin.site.urls),
    path('administrator/', include('administrator.urls')),
    path('voting/', include('voting.urls')),
    path('board_member/', include('board_member.urls')),
    path('candidate/', include('candidate.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index),
    path('dashboard/', views.dashboard, name='voterDashboard'),
    path('electionpage/', views.electionpage, name='electionpage'),
    path('nominate/', views.nominate_candidate, name='nominate_candidate'),
        
    path('vote/', views.vote, name='vote'),
    path('ballot/fetch/', views.fetch_ballot, name='fetch_ballot'),
    path('ballot/vote', views.show_ballot, name='show_ballot'),
    path('ballot/vote/preview', views.preview_vote, name='preview_vote'),
    path('ballot/vote/submit', views.submit_ballot, name='submit_ballot'),
    
    path('view_ballot/', views.view_ballot, name='view_ballot'),

    path('resultpage/', views.resultpage, name='resultpage'),

    # path('candidate/platform/<int:candidate_id>/', views.candidate_platform, name='candidate_platform'),

    # path('update_candidate_bio/', views.update_candidate_bio, name='update_candidate_bio'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting/models.py
from django.db import models
from account.models import CustomUser
# Create your models here.

from django.db import models
from cryptography.fernet import Fernet

class Voter(models.Model):
    admin = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=11, unique=True)  
    voted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.admin.last_name}, {self.admin.first_name}"


class Position(models.Model):
    name = models.CharField(max_length=50, unique=True)
    priority = models.IntegerField()

    def __str__(self):
        return self.name


class Candidate(models.Model):
    fullname = models.CharField(max_length=50)
    photo = models.ImageField(upload_to="candidates")
    bio = models.TextField()
    video = models.FileField(upload_to='candidate_videos/', null=True, blank=True)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    
    # POSITIONS = (
    #     ('President', 'President'),
    #     # Add more positions as needed
    # )

    # fullname = models.CharField(max_length=50)
    # bio = models.TextField()
    # position = models.CharField(max_length=50, choices=POSITIONS, default='President')

    def __str__(self):
        return self.fullname



# Define a function to encrypt and decrypt data
# def encrypt_data(data):
#     # Replace 'YOUR_ENCRYPTION_KEY' with your own encryption key
#     key = b'YOUR_ENCRYPTION_KEY'
#     cipher_suite = Fernet(key)
#     encrypted_data = cipher_suite.encrypt(data.encode())
#     return encrypted_data.decode()

# def decrypt_data(encrypted_data):
#     key = b'YOUR_ENCRYPTION_KEY'
#     cipher_suite = Fernet(key)
#     decrypted_data = cipher_suite.decrypt(encrypted_data.encode())
#     return decrypted_data.decode()

# Define the Votes model with encrypted fields
class Votes(models.Model):
    voter = models.ForeignKey(Voter, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    candidate = models.CharField(max_length=100)  # Assuming max length for candidate names

   

class Nominee(models.Model):
    POSITIONS = (
        ('President', 'President'),
        # Add more positions as needed
    )

    fullname = models.CharField(max_length=50)
    bio = models.TextField()
    position = models.CharField(max_length=50, choices=POSITIONS, default='President')
    is_approved = models.BooleanField('Approved', default=False)

    def __str__(self):
        return self.fullname

voting/forms.py
from django import forms
from .models import *
from account.forms import FormSettings


class VoterForm(FormSettings):
    class Meta:
        model = Voter
        fields = ['phone_number']


class PositionForm(FormSettings):
    class Meta:
        model = Position
        fields = ['name']
        
    def clean_name(self):
        first_name = self.cleaned_data['name']
        if not first_name.isalpha():
            raise forms.ValidationError("Position name should only contain letters")
        return first_name


from django import forms
from django.core.exceptions import ValidationError
from .models import Candidate

class CandidateForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = ['fullname', 'bio', 'position', 'photo', 'video']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

    def clean_fullname(self):
        fullname = self.cleaned_data.get('fullname')
        position = self.cleaned_data.get('position')
        
        if Candidate.objects.filter(fullname=fullname, position=position).exists():
            raise ValidationError(f"A candidate with the name {fullname} already exists for this position.")
        
        return fullname

    def clean_photo(self):
        photo = self.cleaned_data.get('photo')
        if photo:
            max_size = 10 * 1024 * 1024  # 10 MB
            if photo.size > max_size:
                raise ValidationError("The maximum file size allowed is 10MB.")
            if not photo.content_type.startswith('image'):
                raise ValidationError("Unsupported file format. Please upload a JPEG, PNG, or GIF.")
        return photo

    def clean_video(self):
        video = self.cleaned_data.get('video')
        if video:
            max_size = 50 * 1024 * 1024  # 50 MB
            if video.size > max_size:
                raise ValidationError("The maximum file size allowed is 50MB.")
            if not video.content_type.startswith('video'):
                raise ValidationError("Unsupported file format. Please upload an MP4, MPEG, or QuickTime video.")
        return video


class NomineeForm(FormSettings):
    class Meta:
        model = Nominee
        fields = ['fullname', 'bio']

voting/views.py
from django.shortcuts import render, redirect, reverse
from account.views import account_login
from board_member.forms import ElectionPost
from board_member.models import ElectionResult
from .models import Nominee, Position, Candidate, Voter, Votes
from django.http import JsonResponse
from django.utils.text import slugify
from django.contrib import messages
from django.conf import settings
from django.http import JsonResponse
import requests
import json

# Create your views here.


def index(request):
    if not request.user.is_authenticated:
        return account_login(request)
    context = {}
    return render(request, "voting/login.html", context)


def dashboard(request):
    user = request.user
    if user.voter.voted:  # User has voted
        context = {
            "my_votes": Votes.objects.filter(voter=user.voter),
        }
        return redirect(reverse("vote"))
    else:
        return redirect(reverse("electionpage"))

def vote(request):
    return render(request, "voting/voter/myvote.html")

def electionpage(request):
    # return render(request, "voting/voter/votingandnominatingpage.html")
    return redirect(reverse("show_ballot"))








def view_ballot(request):
    if request.user.is_authenticated:
        voter = request.user.voter
        try:
            vote = Votes.objects.get(voter=voter)
            context = {
                'vote': vote
            }
            return render(request, 'voting/voter/view_ballot.html', context)
        except Votes.DoesNotExist:
            return render(request, 'voting/voter/no_vote.html')
    else:
        return redirect('login')  # Redirect to login page if user is not authenticated 
    
    
def generate_ballot(display_controls=False):
    electionposts = ElectionPost.objects.filter(is_posted=True)
    falseelectionposts = ElectionPost.objects.filter(is_posted=False)
    positions = Position.objects.order_by("priority").all()
    output = ""
    candidates_data = ""
    num = 1
    for position in positions:
        name = position.name
        position_name = slugify(name)
        candidates = Candidate.objects.filter(position=position)
        for candidate in candidates:
            input_box = (
                '<input value="'
                + str(candidate.id)
                + '" type="radio" class="flat-red '
                + position_name
                + '" name="'
                + position_name
                + '">'
            )
            image = "/media/" + str(candidate.photo)
            candidates_data = (
                candidates_data
                + "<li>"
                + input_box
                + '<button type="button" class="btn btn-primary btn-sm btn-flat clist platform" data-fullname="'
                + candidate.fullname
                + '" data-bio="'
                + candidate.bio
                + '"><i class="fa fa-search"></i> Platform</button><img src="'
                + image
                + '" height="100px" width="100px" class="clist"><span class="cname clist">'
                + candidate.fullname
                + "</span></li>"
            )
        up = ""
        if position.priority == 1:
            up = "disabled"
        down = ""
        if position.priority == positions.count():
            down = "disabled"
        output += f"""<div class="row">	<div class="col-xs-12"><div class="box box-solid" id="{position.id}">
             <div class="box-header with-border">
            <h3 class="box-title"><b>{name}</b></h3>"""

        if display_controls:
            output += f""" <div class="pull-right box-tools">
        <button type="button" class="btn btn-default btn-sm moveup" data-id="{position.id}" {up}><i class="fa fa-arrow-up"></i> </button>
        <button type="button" class="btn btn-default btn-sm movedown" data-id="{position.id}" {down}><i class="fa fa-arrow-down"></i></button>
        </div>"""

        output += f"""</div>
        <div class="box-body">
        <p>Select only one candidate
        <span class="pull-right">
        <button type="button" class="btn btn-success btn-sm btn-flat reset" data-desc="{position_name}"><i class="fa fa-refresh"></i> Reset</button>
        </span>
        </p>
        <div id="candidate_list">
        <ul>
        {candidates_data}
        </ul>
        </div>
        </div>
        </div>
        </div>
        </div>
        """
        position.priority = num
        position.save()
        num += 1
        candidates_data = ""
    return output


def fetch_ballot(request):
    output = generate_ballot(display_controls=True)
    return JsonResponse(output, safe=False)




def show_ballot(request):
    electionposts = ElectionPost.objects.filter(is_posted=True)
    falseelectionposts = ElectionPost.objects.filter(is_posted=False)
    candidates = Candidate.objects.all()  # Using a more intuitive variable name
    if request.user.voter.voted:
        messages.error(request, "You have voted already")
        return redirect(reverse("voterDashboard"))
    ballot = generate_ballot(display_controls=False)
    context = {
        "ballot": ballot,
        'electionposts': electionposts,
        'candidates': candidates,  # Updated variable name
    }
    return render(request, "voting/voter/ballot.html", context)


def preview_vote(request):
    electionposts = ElectionPost.objects.filter(is_posted=True)
    falseelectionposts = ElectionPost.objects.filter(is_posted=False)
    if request.method != "POST":
        error = True
        response = "Please browse the system properly"
    else:
        output = ""
        form = dict(request.POST)
        form.pop("csrfmiddlewaretoken", None)
        error = False
        data = []
        positions = Position.objects.all()
        for position in positions:
            pos = slugify(position.name)
            if pos in form:
                form_position = form[pos][0]
                candidate = Candidate.objects.get(position=position, id=form_position)
                output += f"""
                        <div class='row votelist' style='padding-bottom: 2px'>
                          	<span class='col-sm-4'><span class='pull-right'><b>{position.name} :</b></span></span>
                          	<span class='col-sm-8'><i class="fa fa-check-circle-o"></i> {candidate.fullname}</span>
                        </div>
                        <hr/>
                    """
    context = {"error": error, "list": output}
    return JsonResponse(context, safe=False)

from django.shortcuts import render, redirect
from .models import Votes, Nominee  # Import your models here
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import Votes, Nominee
from django.contrib import messages

from .models import Voter, Votes, Nominee


def submit_ballot(request):
    if request.method == 'POST':
        selected_candidate_id = request.POST.get('selected_candidate')
        if selected_candidate_id:
            try:
                selected_candidate = Candidate.objects.get(pk=selected_candidate_id)
                candidate_name = selected_candidate.fullname
                
                if request.user.is_authenticated:
                    voter = request.user.voter
                    # Check if the voter has already voted
                    if Votes.objects.filter(voter=voter).exists():
                        return redirect('vote')
                    else:
                        # Retrieve the Position instance for 'President'
                        president_position, _ = Position.objects.get_or_create(name='President', defaults={'priority': 1})
                        
                        # Create the Vote instance
                        vote = Votes.objects.create(voter=voter, position=president_position, candidate=candidate_name)
                        vote.save()
                        messages.success(request, f'Vote submitted successfully for {candidate_name}.')
                else:
                    messages.error(request, 'User is not authenticated.')
            except Nominee.DoesNotExist:
                messages.error(request, 'Selected candidate does not exist.')
        else:
            messages.error(request, '') #   No candidate selected.
        return redirect('electionpage')
    else:
        return redirect('electionpage')


from administrator.views import PrintView  # Import the PrintView class

def resultpage(request):
    resultpage = ElectionResult.objects.filter(isposted=True)
    falseresultpage = ElectionResult.objects.filter(isposted=False)
    # Instantiate the PrintView class to generate context data
    print_view = PrintView()
    # context = print_view.get_context_data()
    # context = {'resultpage' : resultpage}
    
    context = {**print_view.get_context_data(), 'resultpage': resultpage}


    # Render the template with the context data
    return render(request, "voting/voter/ResultPage.html", context)


# def candidate_platform(request, candidate_id):
#     try:
#         candidate = Candidate.objects.get(pk=candidate_id)
#         data = {
#             'fullname': candidate.fullname,
#             'bio': candidate.bio,
#         }
#         return JsonResponse(data)
#     except Candidate.DoesNotExist:
#         return JsonResponse({'error': 'Candidate does not exist'}, status=404)




# from .models import CampaignMessage
# from .models import Ballot

# def match_names_and_link():
#     campaign_messages = CampaignMessage.objects.all()
#     ballots = Ballot.objects.all()

#     for message in campaign_messages:
#         for ballot in ballots:
#             if message.candidate_name == ballot.candidate_name:
#                 message.ballot_id = ballot.id
#                 message.save()
#                 break  # Once a match is found, break out of the inner loop






    
# def submit_ballot(request):
#     if request.method != "POST":

voting/templates/voting/voter/nomination_form.html
<!-- nomination_form.html -->
{% load static %}
{% block content %}
<section>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport"
            content="width=device-width, initial-scale=1, minimum-scale=1">
        <link rel="shortcut icon"
            href="{% static 'assets/images/logo.png-1-120x126.jpeg' %}"
            type="image/x-icon">
        <meta name="description"
            content="Revolutionizing the voting experience with cutting-edge technology. Say goodbye to long queues and hello to convenience.">
        <title>Haramaya University Student Union Election</title>
        <link rel="stylesheet"
            href="{% static 'assets/web/assets/mobirise-icons2/mobirise2.css' %}">
        <link rel="stylesheet"
            href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet"
            href="{% static 'assets/bootstrap/css/bootstrap-grid.min.css' %}">
        <link rel="stylesheet"
            href="{% static 'assets/bootstrap/css/bootstrap-reboot.min.css' %}">
        <link rel="stylesheet"
            href="{% static 'assets/parallax/jarallax.css' %}">
        <link rel="stylesheet"
            href="{% static 'assets/dropdown/css/style.css' %}">
        <link rel="stylesheet"
            href="{% static 'assets/socicon/css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'assets/theme/css/style.css' %}">
        <link rel="preload"
            href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap&display=swap"
            as="style" onload="this.onload=null;this.rel='stylesheet'">
        <noscript>
            <link rel="stylesheet"
                href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap&display=swap">
        </noscript>
        <link rel="preload" as="style"
            href="{% static 'assets/mobirise/css/mbr-additional.css?v=BlP0Wv' %}">
        <link rel="stylesheet"
            href="{% static 'assets/mobirise/css/mbr-additional.css?v=BlP0Wv' %}"
            type="text/css">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js">
        </script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="">
            <div class="container-fluid">
                <!-- Add the logo and text -->
                <a class="navbar-brand" href="#">
                    <img src="{% static 'assets/images/logo.png-1-120x126.jpeg' %}"
                        alt="HUEVS Logo" width="30" height="50"
                        class="d-inline-block align-top">
                    <a href="" style="color:black;"> HUEVS </a>
                </a>
                <!-- Add the toggle button for small screens -->
                <button class="navbar-toggler" type="button"
                    data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Add the navigation links -->
                <div class="collapse navbar-collapse justify-content-between"
                    id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <!-- Navigation items -->
                    </ul>
                    <!-- Add the buttons -->
                    <div class="navbar-buttons mbr-section-btn">
                        {% comment %} <button class="btn btn-primary dropdown-toggle"
                            type="button" id="profileDropdown"
                            data-toggle="dropdown" aria-haspopup="true"
                            aria-expanded="false">
                            Profile
                        </button> {% endcomment %}
                        {% comment %} <div class="dropdown-menu"
                            aria-labelledby="profileDropdown">
                            <!-- Check if user is authenticated -->
                            <!-- If authenticated, show profile and logout options -->
                            <a class="dropdown-item" href="#">Edit Profile</a>
                            <!-- If not authenticated, show login and register options -->
                            <a class="dropdown-item"
                                href="{% url 'account_logout' %}">Logout</a>
                        </div> {% endcomment %}
                        <a class="btn btn-primary"
                            href="{% url 'nominate_candidate' %}"
                            style="border-radius: 15px;">Nominate</a>
                        <a class="btn btn-primary"
                            href="{% url 'show_ballot' %}"
                            style="border-radius: 15px;">Vote</a>
                        <a class="btn btn-primary" href="{% url 'resultpage' %}"
                            style="border-radius: 15px;">Result</a>
                        <a class="btn btn-primary"
                            href="{% url 'account_logout' %}"
                            style="border-radius: 15px;">Logout</a>
                    </div>
                </div>
            </div>
        </nav>
        <br> <br>
        <br> <br>
        {%if nominationposts %}
        <h1 class="page-header text-center title"><b>Haramaya University Student
                Union President Nomination</b></h1>
        <section class="content">
            <br>
            <style>
                @import url(https://fonts.googleapis.com/css?family=Lato:100,400);
                #the-final-countdown {
                        {
                        % comment %
                    }
                    background: blue;
                        {
                        % endcomment %
                    }
                    font-family: 'Lato',
                    sans-serif;
                    text-align: center;
                    color: black;
                    text-shadow: 1px 1px 5px black;
                    font-size: 3rem;
                    border-radius: 45px;
                    width: 1200px;
                    margin-left: 70px;
                }
            </style>
            </head>
            {% comment %}
            <body>
                <div id="the-final-countdown">
                    <p></p>
                </div>
                <script
                    src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
                </script>
                <script>
                    setInterval(function time() {
                        var d = new Date();
                        var hours = 24 - d.getHours();
                        var min = 60 - d.getMinutes();
                        if ((min + '').length == 1) {
                            min = '0' + min;
                        }
                        var sec = 60 - d.getSeconds();
                        if ((sec + '').length == 1) {
                            sec = '0' + sec;
                        }
                        jQuery('#the-final-countdown p').html(hours +
                            ':' +
                            min + ':' + sec)
                    }, 1000);
                </script>
            </body>
            </html> {% endcomment %}
            <section
                style="margin: 0 auto; height: 500px; max-width: 900px; padding-left: 30px; padding-right: 30px; border: 2px solid #ccc; border-radius: 30px;">
                <br>
                <h1 class="page-header text-center title"><b>Nominate a
                        Candidate</b></h1>
                        <form id="nomination-form" method="post" class="form-group">
                            {% csrf_token %}
                    <div class="form-group">
                        <label for="id_fullname" class="form-label">Full
                            Name</label>
                        <input type="text" name="fullname" id="id_fullname"
                            class="form-control" placeholder="Enter full name"
                            required>
                    </div>
                    <div class="form-group">
                        <label for="id_bio" class="form-label">Bio</label>
                        <textarea name="bio" id="id_bio" class="form-control"
                            placeholder="Enter bio" rows="5"
                            required></textarea>
                    </div>
                    <div style="padding-left: 260px;">
                        <button id="submit-btn" type="submit"
                            class="btn btn-primary">Submit Nomination</button>
                    </div>
                </form>
            </section>
            {%else%}
            <section
                style="margin: 100 auto; max-width: 1600px; padding: 20px; ">
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body text-center">
                                <h1 class="card-title">Sorry, It's Not
                                    Nomination Time</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            {%endif%}
        </section>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script>
    $(document).ready(function() {
        $('#nomination-form').submit(function(e) {
            e.preventDefault();
            var form = $(this);
            // Disable the submit button to prevent multiple submissions
            $('#submit-btn').prop('disabled', true);
            // Perform form submission via AJAX
            $.ajax({
                type: form.attr('method'),
                url: form.attr('action'),
                data: form.serialize(),
                success: function(response) {
                    // Display success message using Sweet Alert
                    Swal.fire({
                        icon: 'success',
                        title: 'Nomination Submitted!',
                        text: 'Thank you for your nomination.',
                        showConfirmButton: false,
                        timer: 2000,
                        position: 'top-end' // Set position to top right corner
                    });
                    // Clear form fields
                    form.trigger('reset');
                },
                error: function(xhr, errmsg, err) {
                    // Enable the submit button
                    $('#submit-btn').prop('disabled', false);
                    // Display error message using Sweet Alert
                    Swal.fire({
                        icon: 'error',
                        title: 'Oops...',
                        text: 'An error occurred while submitting the nomination. Please check your inputs.',
                        position: 'top-end' // Set position to top right corner
                    });
                }
            });
        });
    });
</script>
{% endblock content %}